twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        test_globals: 'my custom global'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'